# Generated by Django 5.2.1 on 2025-05-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=10)),
                ('disponibles', models.PositiveIntegerField()),
            ],
        ),
    ]
